In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

C:\Users\Abhinaba\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\Abhinaba\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\Abhinaba\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\Abhinaba\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWa

In [2]:
tf.__version__

'1.14.0'

In [3]:
#import the dataset
#df=pd.read_excel("airfoil_self_noise.xlsx")
df=pd.read_excel("airfoil_self_noise.xlsx")
df.head(1)

Frequency  AngleOfAttack  Chord_Length  FreeStreamVelocity  \
0        800            0.0        0.3048                71.3   

   SuctionSideDispacementThickness  ScaledSoundPressureLevel  
0                         0.002663                   126.201

In [4]:
x=df.drop(['ScaledSoundPressureLevel'],axis=1)
x.head(1)

Frequency  AngleOfAttack  Chord_Length  FreeStreamVelocity  \
0        800            0.0        0.3048                71.3   

   SuctionSideDispacementThickness  
0                         0.002663

In [5]:
y=df[['ScaledSoundPressureLevel']]
y.head(1)

ScaledSoundPressureLevel
0                   126.201

In [6]:
#split the dataset
from sklearn.model_selection import train_test_split

In [7]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25, random_state=2)

In [24]:
from sklearn import preprocessing
max_abs_scaler = preprocessing.MinMaxScaler()
x = preprocessing.MinMaxScaler(x)
x_test = preprocessing.MinMaxScaler(x_test)
#y_train = max_abs_scaler.fit_transform(y_train)
#y_test = max_abs_scaler.fit_transform(y_test)

In [25]:
x

MinMaxScaler(copy=True,
             feature_range=array([[-0.66, -1.15,  1.8 ,  1.31, -0.64],
       [-0.6 , -1.15,  1.8 ,  1.31, -0.64],
       [-0.52, -1.15,  1.8 ,  1.31, -0.64],
       ...,
       [ 0.35,  1.49, -0.37, -0.72,  3.17],
       [ 0.67,  1.49, -0.37, -0.72,  3.17],
       [ 1.08,  1.49, -0.37, -0.72,  3.17]]))

In [9]:
#building the ANN
annModel=tf.keras.models.Sequential()

In [10]:
#adding the input layer and first input layer
annModel.add(tf.keras.layers.Dense(units=50, activation="relu")) #dense they are fully conncted to hidden layer neurons
#second hidden layer
annModel.add(tf.keras.layers.Dense(units=50, activation="relu")) #will be connected automatically
annModel.add(tf.keras.layers.Dense(units=50, activation="relu"))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [11]:
#create the output layer
annModel.add(tf.keras.layers.Dense(units=1)) #as we are doing output layer no activation function normally

In [12]:
#compiling the ann
annModel.compile(optimizer="adam",loss="mean_squared_error")

In [13]:
#build the annModel
#converting it to pandas dataframe to numpy array
x_train=np.array(x)
y_train=np.array(y)
annModel.fit(x_train,y_train,batch_size=16,epochs=1000)

Epoch 1/1000
1503/1503 [==============================] - 1s 351us/sample - loss: 13123.7788
Epoch 2/1000
1503/1503 [==============================] - 0s 141us/sample - loss: 1140.5933
Epoch 3/1000
1503/1503 [==============================] - 0s 170us/sample - loss: 362.1105
Epoch 4/1000
1503/1503 [==============================] - 0s 144us/sample - loss: 286.8378
Epoch 5/1000
1503/1503 [==============================] - 0s 143us/sample - loss: 226.5634
Epoch 6/1000
1503/1503 [==============================] - 0s 136us/sample - loss: 188.5506
Epoch 7/1000
1503/1503 [==============================] - 0s 145us/sample - loss: 153.7108
Epoch 8/1000
1503/1503 [==============================] - 0s 168us/sample - loss: 126.8108
Epoch 9/1000
1503/1503 [==============================] - 0s 181us/sample - loss: 105.3778
Epoch 10/1000
1503/1503 [==============================] - 0s 157us/sample - loss: 85.4239
Epoch 11/1000
1503/1503 [==============================] - 0s 171us/sample - loss: 71.3

1503/1503 [==============================] - 0s 160us/sample - loss: 7.5064
Epoch 92/1000
1503/1503 [==============================] - 0s 150us/sample - loss: 7.7062
Epoch 93/1000
1503/1503 [==============================] - 0s 130us/sample - loss: 7.8039
Epoch 94/1000
1503/1503 [==============================] - 0s 146us/sample - loss: 7.3602
Epoch 95/1000
1503/1503 [==============================] - 0s 152us/sample - loss: 7.5489
Epoch 96/1000
1503/1503 [==============================] - 0s 163us/sample - loss: 7.2303
Epoch 97/1000
1503/1503 [==============================] - 0s 160us/sample - loss: 7.0169
Epoch 98/1000
1503/1503 [==============================] - 0s 137us/sample - loss: 6.6790
Epoch 99/1000
1503/1503 [==============================] - 0s 153us/sample - loss: 6.8146
Epoch 100/1000
1503/1503 [==============================] - 0s 158us/sample - loss: 7.0181
Epoch 101/1000
1503/1503 [==============================] - 0s 143us/sample - loss: 7.1247
Epoch 102/1000
1503/15

1503/1503 [==============================] - 0s 182us/sample - loss: 4.4762
Epoch 182/1000
1503/1503 [==============================] - 0s 178us/sample - loss: 4.4109
Epoch 183/1000
1503/1503 [==============================] - 0s 166us/sample - loss: 4.5898
Epoch 184/1000
1503/1503 [==============================] - 0s 142us/sample - loss: 6.7515
Epoch 185/1000
1503/1503 [==============================] - 0s 146us/sample - loss: 5.2065
Epoch 186/1000
1503/1503 [==============================] - 0s 178us/sample - loss: 4.9118
Epoch 187/1000
1503/1503 [==============================] - 0s 133us/sample - loss: 5.0505
Epoch 188/1000
1503/1503 [==============================] - 0s 131us/sample - loss: 4.7300
Epoch 189/1000
1503/1503 [==============================] - 0s 146us/sample - loss: 4.6744
Epoch 190/1000
1503/1503 [==============================] - 0s 151us/sample - loss: 4.5870
Epoch 191/1000
1503/1503 [==============================] - 0s 158us/sample - loss: 4.9533
Epoch 192/1000

Epoch 271/1000
1503/1503 [==============================] - 0s 149us/sample - loss: 4.3980
Epoch 272/1000
1503/1503 [==============================] - 0s 152us/sample - loss: 4.1890
Epoch 273/1000
1503/1503 [==============================] - 0s 145us/sample - loss: 3.9427
Epoch 274/1000
1503/1503 [==============================] - 0s 148us/sample - loss: 3.7232
Epoch 275/1000
1503/1503 [==============================] - 0s 158us/sample - loss: 3.7187
Epoch 276/1000
1503/1503 [==============================] - 0s 164us/sample - loss: 4.2920
Epoch 277/1000
1503/1503 [==============================] - 0s 138us/sample - loss: 4.2873
Epoch 278/1000
1503/1503 [==============================] - 0s 128us/sample - loss: 4.2746
Epoch 279/1000
1503/1503 [==============================] - 0s 151us/sample - loss: 3.8374
Epoch 280/1000
1503/1503 [==============================] - 0s 146us/sample - loss: 3.8356
Epoch 281/1000
1503/1503 [==============================] - 0s 142us/sample - loss: 3.8816

1503/1503 [==============================] - 0s 150us/sample - loss: 3.8425
Epoch 361/1000
1503/1503 [==============================] - 0s 151us/sample - loss: 3.6107
Epoch 362/1000
1503/1503 [==============================] - 0s 136us/sample - loss: 3.7258
Epoch 363/1000
1503/1503 [==============================] - 0s 132us/sample - loss: 3.8791
Epoch 364/1000
1503/1503 [==============================] - 0s 156us/sample - loss: 4.5211
Epoch 365/1000
1503/1503 [==============================] - 0s 144us/sample - loss: 4.0323
Epoch 366/1000
1503/1503 [==============================] - 0s 144us/sample - loss: 4.3214
Epoch 367/1000
1503/1503 [==============================] - 0s 136us/sample - loss: 4.3873
Epoch 368/1000
1503/1503 [==============================] - 0s 131us/sample - loss: 3.8888
Epoch 369/1000
1503/1503 [==============================] - 0s 148us/sample - loss: 4.0228
Epoch 370/1000
1503/1503 [==============================] - 0s 145us/sample - loss: 3.8656
Epoch 371/1000

1503/1503 [==============================] - 0s 171us/sample - loss: 3.5124
Epoch 450/1000
1503/1503 [==============================] - 0s 167us/sample - loss: 3.5249
Epoch 451/1000
1503/1503 [==============================] - 0s 188us/sample - loss: 4.2417
Epoch 452/1000
1503/1503 [==============================] - 0s 164us/sample - loss: 3.5181
Epoch 453/1000
1503/1503 [==============================] - 0s 152us/sample - loss: 3.5332
Epoch 454/1000
1503/1503 [==============================] - 0s 144us/sample - loss: 3.3494
Epoch 455/1000
1503/1503 [==============================] - 0s 150us/sample - loss: 3.8246
Epoch 456/1000
1503/1503 [==============================] - 0s 144us/sample - loss: 3.4138
Epoch 457/1000
1503/1503 [==============================] - 0s 138us/sample - loss: 3.4617
Epoch 458/1000
1503/1503 [==============================] - 0s 134us/sample - loss: 3.6156
Epoch 459/1000
1503/1503 [==============================] - 0s 140us/sample - loss: 4.0254
Epoch 460/1000

1503/1503 [==============================] - 0s 215us/sample - loss: 3.2743
Epoch 539/1000
1503/1503 [==============================] - 0s 194us/sample - loss: 3.3392
Epoch 540/1000
1503/1503 [==============================] - 0s 237us/sample - loss: 3.2506
Epoch 541/1000
1503/1503 [==============================] - 0s 232us/sample - loss: 3.3190
Epoch 542/1000
1503/1503 [==============================] - 0s 214us/sample - loss: 3.6365
Epoch 543/1000
1503/1503 [==============================] - 0s 249us/sample - loss: 3.1371
Epoch 544/1000
1503/1503 [==============================] - 0s 236us/sample - loss: 3.0527
Epoch 545/1000
1503/1503 [==============================] - 0s 216us/sample - loss: 3.1105
Epoch 546/1000
1503/1503 [==============================] - 0s 242us/sample - loss: 3.8760
Epoch 547/1000
1503/1503 [==============================] - 0s 232us/sample - loss: 2.8991
Epoch 548/1000
1503/1503 [==============================] - 0s 231us/sample - loss: 3.4859
Epoch 549/1000

1503/1503 [==============================] - 0s 185us/sample - loss: 2.9607
Epoch 628/1000
1503/1503 [==============================] - 0s 145us/sample - loss: 3.3173
Epoch 629/1000
1503/1503 [==============================] - 0s 142us/sample - loss: 2.5924
Epoch 630/1000
1503/1503 [==============================] - 0s 155us/sample - loss: 2.7707
Epoch 631/1000
1503/1503 [==============================] - 0s 172us/sample - loss: 3.5433
Epoch 632/1000
1503/1503 [==============================] - 0s 180us/sample - loss: 2.9859
Epoch 633/1000
1503/1503 [==============================] - 0s 174us/sample - loss: 3.1639
Epoch 634/1000
1503/1503 [==============================] - 0s 163us/sample - loss: 2.8697
Epoch 635/1000
1503/1503 [==============================] - 0s 158us/sample - loss: 3.6052
Epoch 636/1000
1503/1503 [==============================] - 0s 275us/sample - loss: 3.4515
Epoch 637/1000
1503/1503 [==============================] - 0s 168us/sample - loss: 3.0708
Epoch 638/1000

1503/1503 [==============================] - 0s 182us/sample - loss: 2.8967
Epoch 717/1000
1503/1503 [==============================] - 0s 196us/sample - loss: 3.2428
Epoch 718/1000
1503/1503 [==============================] - 0s 190us/sample - loss: 2.8211
Epoch 719/1000
1503/1503 [==============================] - 0s 199us/sample - loss: 3.1657
Epoch 720/1000
1503/1503 [==============================] - 0s 205us/sample - loss: 2.6998
Epoch 721/1000
1503/1503 [==============================] - 0s 184us/sample - loss: 2.7201
Epoch 722/1000
1503/1503 [==============================] - 0s 199us/sample - loss: 2.9665
Epoch 723/1000
1503/1503 [==============================] - 0s 162us/sample - loss: 2.8728
Epoch 724/1000
1503/1503 [==============================] - 0s 156us/sample - loss: 2.9411
Epoch 725/1000
1503/1503 [==============================] - 0s 170us/sample - loss: 2.5010
Epoch 726/1000
1503/1503 [==============================] - 0s 153us/sample - loss: 2.8289
Epoch 727/1000

1503/1503 [==============================] - 0s 201us/sample - loss: 2.4985
Epoch 807/1000
1503/1503 [==============================] - 0s 180us/sample - loss: 2.5920
Epoch 808/1000
1503/1503 [==============================] - 0s 188us/sample - loss: 2.6057
Epoch 809/1000
1503/1503 [==============================] - 0s 179us/sample - loss: 3.0064
Epoch 810/1000
1503/1503 [==============================] - 0s 186us/sample - loss: 2.8579
Epoch 811/1000
1503/1503 [==============================] - 0s 182us/sample - loss: 2.4917s - loss: 2.5
Epoch 812/1000
1503/1503 [==============================] - 0s 172us/sample - loss: 2.4425
Epoch 813/1000
1503/1503 [==============================] - 0s 177us/sample - loss: 2.8880
Epoch 814/1000
1503/1503 [==============================] - 0s 182us/sample - loss: 2.8700
Epoch 815/1000
1503/1503 [==============================] - 0s 146us/sample - loss: 2.6265
Epoch 816/1000
1503/1503 [==============================] - 0s 139us/sample - loss: 2.6474
E

1503/1503 [==============================] - 0s 164us/sample - loss: 2.6451
Epoch 896/1000
1503/1503 [==============================] - 0s 138us/sample - loss: 2.1758
Epoch 897/1000
1503/1503 [==============================] - 0s 135us/sample - loss: 2.4709
Epoch 898/1000
1503/1503 [==============================] - 0s 140us/sample - loss: 2.1326
Epoch 899/1000
1503/1503 [==============================] - 0s 138us/sample - loss: 2.5231
Epoch 900/1000
1503/1503 [==============================] - 0s 144us/sample - loss: 2.7208
Epoch 901/1000
1503/1503 [==============================] - 0s 133us/sample - loss: 2.5762
Epoch 902/1000
1503/1503 [==============================] - 0s 140us/sample - loss: 2.3873
Epoch 903/1000
1503/1503 [==============================] - 0s 142us/sample - loss: 2.5427
Epoch 904/1000
1503/1503 [==============================] - 0s 136us/sample - loss: 2.7723
Epoch 905/1000
1503/1503 [==============================] - 0s 146us/sample - loss: 2.4131
Epoch 906/1000

1503/1503 [==============================] - 0s 176us/sample - loss: 2.6258
Epoch 985/1000
1503/1503 [==============================] - 0s 156us/sample - loss: 2.1412
Epoch 986/1000
1503/1503 [==============================] - 0s 182us/sample - loss: 2.1396
Epoch 987/1000
1503/1503 [==============================] - 0s 162us/sample - loss: 2.0875
Epoch 988/1000
1503/1503 [==============================] - 0s 171us/sample - loss: 2.2279
Epoch 989/1000
1503/1503 [==============================] - 0s 151us/sample - loss: 2.4373
Epoch 990/1000
1503/1503 [==============================] - 0s 163us/sample - loss: 2.2111
Epoch 991/1000
1503/1503 [==============================] - 0s 168us/sample - loss: 1.9356
Epoch 992/1000
1503/1503 [==============================] - 0s 182us/sample - loss: 2.2022
Epoch 993/1000
1503/1503 [==============================] - 0s 198us/sample - loss: 2.2240
Epoch 994/1000
1503/1503 [==============================] - 0s 157us/sample - loss: 2.1047
Epoch 995/1000

In [14]:
#predict the test set
from sklearn.metrics import mean_squared_error
x_test=np.array(x_test)
y_test=np.array(y_test)

y_prediction=annModel.predict(x_test)

np.set_printoptions(precision=2)

print(y_prediction)
print(mean_squared_error(y_test, y_prediction))

[[109.18]
 [123.14]
 [121.88]
 [127.48]
 [121.47]
 [133.68]
 [123.83]
 [130.33]
 [128.54]
 [124.  ]
 [118.34]
 [113.96]
 [129.64]
 [129.16]
 [112.68]
 [128.36]
 [132.23]
 [118.01]
 [117.32]
 [120.66]
 [112.84]
 [131.45]
 [129.94]
 [117.54]
 [118.83]
 [119.07]
 [127.99]
 [110.15]
 [127.99]
 [127.84]
 [115.37]
 [122.28]
 [123.5 ]
 [122.55]
 [110.55]
 [130.13]
 [123.13]
 [123.44]
 [108.5 ]
 [122.82]
 [123.74]
 [124.31]
 [133.11]
 [123.91]
 [122.31]
 [121.25]
 [115.28]
 [115.3 ]
 [134.47]
 [120.5 ]
 [134.22]
 [129.87]
 [124.97]
 [124.12]
 [122.15]
 [116.78]
 [126.76]
 [118.85]
 [127.07]
 [125.02]
 [127.04]
 [129.32]
 [127.95]
 [123.53]
 [127.7 ]
 [122.96]
 [123.23]
 [110.84]
 [131.18]
 [129.31]
 [133.75]
 [125.89]
 [124.82]
 [132.92]
 [116.23]
 [128.44]
 [127.84]
 [122.04]
 [119.44]
 [121.06]
 [128.57]
 [133.59]
 [106.56]
 [128.56]
 [130.55]
 [126.24]
 [112.01]
 [129.63]
 [118.21]
 [123.66]
 [131.21]
 [112.7 ]
 [109.58]
 [113.64]
 [130.05]
 [124.12]
 [127.29]
 [122.76]
 [128.46]
 [132.16]


In [15]:
annModel.save('ANN_Model') 

In [16]:
new_model = tf.keras.models.load_model('ANN_Model')

# Check its architecture
new_model.summary()

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                multiple                  300       
_________________________________________________________________
dense_1 (Dense)              multiple                  2550      
_________________________________________________________________
dense_2 (Dense)              multiple                  2550      
_________________________________________________________________
dense_3 (Dense)              multiple                  51        
Total params: 5,451
Trainable params: 5,451
Non-trainable params: 0
_________________________________________________________________


In [17]:
a=np.array([[-0.34,1.0,0.2,-0.77,3.62]])
b=new_model.predict(a)
print(x_test[0])
b
#new_model.predict(x_test[0])

[-0.34  1.    0.2  -0.77  3.62]


array([[109.14]], dtype=float32)

In [19]:
frequency=-0.34
AngleOfAttack=1.0
chordLength=0.2
freeSteamVelocity=-0.77
suctionSideDisplacement=3.62
        
        #create a numpy array to pass in the annmodel
inputParameters=np.array([[frequency,AngleOfAttack,chordLength,freeSteamVelocity,suctionSideDisplacement]])
        
        #load the model
annModel=tf.keras.models.load_model("ANN_Model")
         
        #predict the output, output will be in numpy array format
predicted_output=annModel.predict(inputParameters)

predicted_output

array([[109.14]], dtype=float32)

In [20]:
predicted_output[0][0]

109.14081

In [ ]:
#dataset info

In [ ]:
df=pd.read_excel("airfoil_self_noise.xlsx")
df.head(1)

In [ ]:
df.info()

In [ ]:
df.max()

In [ ]:
df.min()

In [ ]:
x=df.describe()
x.to_csv("Info.csv")
x.head(1)

In [ ]:
x.columns

In [ ]:
y=x.transpose()

In [ ]:
y.columns

In [ ]:
df=pd.read_csv("Info.csv")
df.head(1)

In [ ]:
values=df.drop(['Unnamed: 0'],axis=1)
values.head(1)

In [ ]:
cols=values.columns
cols

In [ ]:
x=df['Unnamed: 0']
rows=np.asarray(x)
rows[0]

In [ ]:
values=np.asarray(values)

In [ ]:
values